name = "nanodrop-files"
compatibility_date = "2022-11-18"
main = "./src/index.ts"

services = [
  { binding = "nanodrop-files", service = "nanodrop-files", environment = "production" }
]

[vars]
B2_APPLICATION_KEY_ID = "005b0439b43c6310000000001"
B2_ENDPOINT = "s3.us-east-005.backblazeb2.com"
BUCKET_NAME = "nanodrop-files"
